export const projects = [
    {
        id: "1",
        title: "POPQUIZ",
        github: "https://github.com/AbhayTopno/PopQuiz",
        demo: null,
        techs: ["Next.js", "TypeScript", "LangChain", "Express.js", "Redis", "Kubernetes", "Terraform"],
        duration: "Oct 2025",
        roles: "Full Stack Developer",
        summary: "AI Powered Scalable Quiz Hosting Platform offering solo and multiplayer modes powered by LangChain and real-time gameplay. Implemented Redis for high-performance in-memory storage of chats, sessions, and live match scores. Automated CI/CD and provisioned infrastructure on GKE via Terraform.",
        image1: "/pq1.mp4",
        image2: "/pq2.png",
        image3: "/pq3.mp4",
        image4: "/pq4.png",
        bg1: "/black_bg.webp",
        bg2: "/pq2.png",
        bg3: "/cloth_bg.webp",
        bg4: "/pq4.png",
        next: "2",
    },
    {
        id: "2",
        title: "CONTRIBUTION HUB",
        github: "https://github.com/AbhayTopno/Contribution-Hub",
        demo: null,
        techs: ["Django", "GraphQL", "PostgreSQL", "Redis", "Next.js", "TypeScript", "Docker"],
        duration: "May 2025",
        roles: "Full Stack Developer",
        summary: "Platform to help contributors find open-source organizations and projects based on skills/interests. Features leaderboards, advanced search filters, and beginner-friendly issue recommendations. Boosted performance using Redis caching and optimized GraphQL resolvers.",
        image1: "/ch1.mp4",
        image2: "/ch2.png",
        image3: "/ch3.mp4",
        image4: "/ch4.png",
        bg1: "/sea_bg.webp",
        bg2: "/ch2.png",
        bg3: "/paper_bg.webp",
        bg4: "/ch4.png",
        next: "1"
    }
] 